server:
  port: 8081
spring:
  application:
    name: configservice
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config/{application}/
      enabled: true
      eureka:
        instance:
          preferIpAddress: true
        client:
          registerWithEureka: true
          fetchRegistry: true
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/
