server:
  port: 8083
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users\xcg1892\Documents\Project\SpringMicroserv\ConfigServer\src\main\resources\config\licencingservice
