server:
  port: 8083
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    h2:
      console:
        enabled: true
  cloud:
    config:
      enabled: true
      eureka:
        instance:
          preferIpAddress: true
        client:
          registerWithEureka: true
          fetchRegistry: true
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/